### ISSUE TITLE
Cannot see urp functioning in Chapter-2

### ISSUE THREAD

**Issue by KunjPrasad** [agazzarini/apache-solr-essentials#16]
In chapter-2 code, I'm doing the following:
1)starting in debug mode, as maven > debug As > start-ch2-server-custom-update-request-processor
2)opening localhost:8983/solr and selecting urp 
3)going to "documents" tab (on right side), and putting json entry: {"id":"id1","isbn":"isbn1","title":"title1_","author":"author1"} and committing in Solr
4)when i query "*:*", it is still showing "title1_". I understood that it should instead be showing "title1" (no underscore at end)
Please if it may be confirmed if something else needs to be done to get the expected result from urp..

**Comment by agazzarini** [comment]
Hi thanks for entering this. I don't have my laptop at the moment so I cannot be sure about what's going wrong. I will try to reproduce your scenario and then I will come back to you with the explanation

**Comment by agazzarini** [comment]
Hi @KunjPrasad,
just pushed a fix for that issue: that was a fault of mine, a wrong
parameter declaration didn't allow a correct recognition of the target
fields.
Now it should be ok: if it is, please close the issue

Many thanks again,
Andrea

2015-07-12 18:20 GMT+02:00 KunjPrasad <notifications@github.com>:

**Comment by KunjPrasad** [comment]
Thanks for the fix (p.s. Wonderful and very helpful book. Thanks)

**Comment by agazzarini** [comment]
you're welcome ;)
